### ISSUE TITLE
Error: Command npm is missing

### ISSUE THREAD

**Issue by headonkeyboard** [Kunstmaan/puphpet#1]
When I do a "vagrant up" for the first time, I get this error 

```
==> default: Error: /Stage[main]/Puphpet_nodejs/Package[uglify-js]/ensure: change from absent to present failed: Command npm is missing  
==> default: Error: Command npm is missing
```

**Comment by dameert** [comment]
npm has changed the location of it's shasums: https://github.com/nodejs/node-gyp/issues/761
This is patched in puphpet: https://github.com/puphpet/puppet-puphpet/blob/master/templates/nodejs/install.erb

But Kunstmaan puphpet should be configured to use a more recent version.

**Comment by konstantinsp** [comment]
created a pull request to fix this) 
https://github.com/Kunstmaan/puphpet/pull/3
